package eu.execom.hawaii.model.enumerations;

public enum LeaveProfileType {
  ZERO_TO_FIVE_YEARS,
  FIVE_TO_TEN_YEARS,
  TEN_TO_FIFTEEN_YEARS,
  FIFTEEN_TO_TWENTY_YEARS,
  TWENTY_TO_TWENTYFIVE_YEARS,
  TWENTYFIVE_TO_THIRTY_YEARS,
  THIRTY_TO_THIRTYFIVE_YEARS,
  THIRTYFIVE_TO_FORTY_YEARS,
  PART_TIME,
  DEFAULT
}

